"""add a categorization for services

Revision ID: 2ac1392f4dce
Revises: d42ec927b761
Create Date: 2026-01-05 12:14:41.011247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ac1392f4dce'
down_revision: Union[str, Sequence[str], None] = 'd42ec927b761'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint('uq_admin_salon_pair', 'admin_salon', ['admin_id', 'salon_id'])
    op.add_column('services', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'services', 'service_category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_column('services', 'category_id')
    op.drop_constraint('uq_admin_salon_pair', 'admin_salon', type_='unique')
    op.drop_table('service_category')
    # ### end Alembic commands ###
