"""add a table for communication between salons and services

Revision ID: 4346cef834bb
Revises: 2ac1392f4dce
Create Date: 2026-01-05 15:32:28.146505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4346cef834bb'
down_revision: Union[str, Sequence[str], None] = '2ac1392f4dce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_salon',
    sa.Column('salon_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('service_id', 'salon_id', name='pk_service_salon'),
    sa.UniqueConstraint('service_id', 'salon_id', name='uq_service_salon_pair')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_salon')
    # ### end Alembic commands ###
