"""Add a schedule table for masters and salons.

Revision ID: 4383b9a876aa
Revises: 4346cef834bb
Create Date: 2026-01-21 18:29:32.528934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4383b9a876aa'
down_revision: Union[str, Sequence[str], None] = '4346cef834bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salon_schedules',
    sa.Column('salon_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('break_start', sa.Time(), nullable=True),
    sa.Column('break_end', sa.Time(), nullable=True),
    sa.Column('is_working', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ),
    sa.PrimaryKeyConstraint('salon_id', 'day_of_week', name='pk_salon_day_of_week'),
    sa.UniqueConstraint('salon_id', 'day_of_week', name='uq_salon_day_of_week_pair')
    )
    op.create_table('master_schedules',
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('salon_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('break_start', sa.Time(), nullable=True),
    sa.Column('break_end', sa.Time(), nullable=True),
    sa.Column('is_working', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['master_id'], ['masters.id'], ),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ),
    sa.PrimaryKeyConstraint('master_id', 'salon_id', 'day_of_week', name='pk_master_salon_day_of_week'),
    sa.UniqueConstraint('master_id', 'salon_id', 'day_of_week', name='uq_master_salon_day_of_week_pair')
    )
    op.create_unique_constraint('uq_service_salon_pair', 'service_salon', ['service_id', 'salon_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_service_salon_pair', 'service_salon', type_='unique')
    op.drop_table('master_schedules')
    op.drop_table('salon_schedules')
    # ### end Alembic commands ###
