"""change the status column in the appointments table so that the corresponding statuses can be assigned to records

Revision ID: 7fc6ad20e2cd
Revises: d22f0e585120
Create Date: 2026-02-22 14:24:06.917752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7fc6ad20e2cd'
down_revision: Union[str, Sequence[str], None] = 'd22f0e585120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Создаем тип ENUM в базе
    status_enum = postgresql.ENUM('pending', 'confirmed', 'completed', 'cancelled', 'no_show', name='appointmentstatus')
    status_enum.create(op.get_bind())
    # op.alter_column('appointments', 'status',
    #            existing_type=sa.BOOLEAN(),
    #            type_=sa.Enum('pending', 'confirmed', 'completed', 'cancelled', 'no_show', name='appointmentstatus'),
    #            server_default='completed')
    
    # 2. Теперь меняем колонку (добавьте USING для конвертации старых данных)
    op.alter_column('appointments', 'status',
               existing_type=sa.BOOLEAN(),
               type_=status_enum,
               postgresql_using="""
        CASE 
            WHEN status = True THEN 'confirmed'::appointmentstatus 
            WHEN status = False THEN 'completed'::appointmentstatus
            ELSE 'pending'::appointmentstatus 
        END
    """) # это важно, если в колонке уже есть данные
    # op.create_unique_constraint('uq_master_salon_day_of_week_pair', 'master_schedules', ['master_id', 'salon_id', 'day_of_week'])
    # op.create_unique_constraint('uq_salon_day_of_week_pair', 'salon_schedules', ['salon_id', 'day_of_week'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('uq_salon_day_of_week_pair', 'salon_schedules', type_='unique')
    # op.drop_constraint('uq_master_salon_day_of_week_pair', 'master_schedules', type_='unique')
    status_enum = postgresql.ENUM('pending', 'confirmed', 'completed', name='appointmentstatus')
    op.alter_column('appointments', 'status',
               existing_type=status_enum,
               type_=sa.BOOLEAN(),
               existing_nullable=False)
    status_enum.drop(op.get_bind())
    # ### end Alembic commands ###
