"""create a review table

Revision ID: 88948c35dda1
Revises: 7fc6ad20e2cd
Create Date: 2026-02-22 20:21:50.039072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88948c35dda1'
down_revision: Union[str, Sequence[str], None] = '7fc6ad20e2cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=True),
    sa.Column('salon_id', sa.Integer(), nullable=True),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('is_moderated', sa.Boolean(), nullable=False),
    sa.Column('reason_for_deletion', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['master_id'], ['masters.id'], ),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_id')
    )
    # op.create_unique_constraint('uq_master_salon_day_of_week_pair', 'master_schedules', ['master_id', 'salon_id', 'day_of_week'])
    # op.create_unique_constraint('uq_salon_day_of_week_pair', 'salon_schedules', ['salon_id', 'day_of_week'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('uq_salon_day_of_week_pair', 'salon_schedules', type_='unique')
    # op.drop_constraint('uq_master_salon_day_of_week_pair', 'master_schedules', type_='unique')
    op.drop_table('reviews')
    # ### end Alembic commands ###
