"""add the reason_for_deletion column to the table of users, salons, appointment and masters, 
 to save the reason for account or record deactivation

Revision ID: d22f0e585120
Revises: 4383b9a876aa
Create Date: 2026-02-13 18:37:33.161136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd22f0e585120'
down_revision: Union[str, Sequence[str], None] = '4383b9a876aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('reason_for_deletion', sa.String(), nullable=True))
    op.add_column('appointments', sa.Column('reason_for_deletion', sa.String(), nullable=True))
    # op.create_unique_constraint('uq_master_salon_day_of_week_pair', 'master_schedules', ['master_id', 'salon_id', 'day_of_week']) ошибка, алембик не видит эту пару, хотя она есть
    op.add_column('masters', sa.Column('reason_for_deletion', sa.String(), nullable=True))
    # op.create_unique_constraint('uq_salon_day_of_week_pair', 'salon_schedules', ['salon_id', 'day_of_week']) ошибка, алембик не видит эту пару, хотя она есть
    op.add_column('salons', sa.Column('reason_for_deletion', sa.String(), nullable=True))
    op.add_column('services', sa.Column('reason_for_deletion', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reason_for_deletion', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reason_for_deletion')
    op.drop_column('services', 'reason_for_deletion')
    op.drop_column('salons', 'reason_for_deletion')
    # op.drop_constraint('uq_salon_day_of_week_pair', 'salon_schedules', type_='unique')
    op.drop_column('masters', 'reason_for_deletion')
    # op.drop_constraint('uq_master_salon_day_of_week_pair', 'master_schedules', type_='unique')
    op.drop_column('appointments', 'reason_for_deletion')
    op.drop_column('admins', 'reason_for_deletion')
    # ### end Alembic commands ###
